apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: hello-node
    spec:     # pod spec                  
      containers: 
      - name: hello-world 
        image: docker.local:5000/monpueng/hellonode:latest # image we pushed
        ports:
        - containerPort: 3000
